/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   tag_rule.h                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: aait-ihi <aait-ihi@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/11/03 18:01:06 by aait-ihi          #+#    #+#             */
/*   Updated: 2020/11/03 19:39:28 by aait-ihi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef TAG_RULE_H
# define TAG_RULE_H

#define L1 "camera:\n"
#define L2 "\tlook_from : vec\n"
#define L3 "\tlook_at : vec\n"
#define L4 "\tscene type : enum : normal , antialiasing, depth of field\n"
#define L5 "\tindirect light : enum: 1,0\n"
#define L6 "\talgo type : enum : simple , multithreading , motionblur\n"

#define L7 "sphere\n"
#define	L8 "\tposition : vec\n"
#define	L9 "\tradius : double\n"
#define	L10 "\tsphere_negatif : enum : 1 , 0\n"
#define	L11 "\tcut_exist : node : limit_xyz1 : vec, limit_xyz2: vec\n"
#define	L12 "\tcolor : vec\n"
#define	L13 "\ttranslation : vec\n"
#define	L14 "\tdiffuse : enum : 1 , 0\n"
#define	L15 "\tspecular : enum : 1 , 0\n"
#define	L16 "\treflection : unsigned int\n"
#define	L17 "\trefraction : unsigned int\n"
#define	L18 "\ttexture : enum : wood , cloud , marble , perlin_noise , damier , xor_noise , toon_shading , normal_perturbation\n"

#define L19 "cone\n"
#define	L20 "\tposition : vec\n"
#define	L21 "\taxis : vec\n"
#define	L22 "\tangle : double\n"
#define	L23 "\tcut_limit1 : double\n"
#define	L24 "\tcut_limit2 : double\n"
#define	L25 "\tcut_exist : node : limit_xyz1 : vec,  limit_xyz2: vec\n"
#define	L26 "\tcolor : vec\n"
#define	L27 "\ttranslation : vec\n"
#define	L28 "\trotation : vec\n"
#define	L29 "\tdiffuse : enum : 1 , 0\n"
#define	L30 "\tspecular : enum : 1 , 0\n"
#define	L31 "\treflection : unsigned int\n"
#define	L32 "\trefraction : unsigned int\n"
#define	L39 "\ttexture : enum : wood , cloud , marble , perlin_noise , damier , xor_noise , toon_shading , normal_perturbation\n"

#define	L34 "cylinder\n"
#define	L35	"\tposition : vec\n"
#define	L36	"\taxis : vec\n"
#define	L37	"\tradius : double\n"
#define	L38	"\tcut_limit : double\n"
#define	L39	"\tcyl_negatif : enum : 1 , 0\n"
#define	L40	"\tcut_exist : node : limit_xyz1 : vec,  limit_xyz2: vec\n"
#define	L41	"\tcolor : vec\n"
#define	L42	"\ttranslation : vec\n"
#define	L43	"\trotation : vec\n"
#define	L44 "\tdiffuse : enum : 1 , 0\n"
#define	L45 "\tspecular : enum : 1 , 0\n"
#define	L46 "\treflection : unsigned int\n"
#define	L47 "\trefraction : unsigned int\n"
#define	L48	"\ttexture : enum : wood , cloud , marble , perlin_noise , damier , xor_noise , toon_shading , normal_perturbation\n"

#define	L49 "plane\n"
#define	L50	"\tposition : vec\n"
#define	L51	"\taxis : vec\n"
#define	L52	"\tcolor : vec\n"
#define	L53	"\ttranslation : vec\n"
#define	L54	"\trotation : vec\n"
#define	L55	"\tdiffuse : enum : 1 , 0\n"
#define	L56 "\tspecular : enum : 1 , 0\n"
#define	L57 "\treflection : unsigned int\n"
#define	L58 "\trefraction : unsigned int\n"
#define	L59	"\ttexture : enum : wood , cloud , marble , perlin_noise , damier , xor_noise\n"

#define	L60	 "disk\n"
#define	L61	"\tposition : vec\n"
#define	L62	"\taxis : vec\n"
#define	L63	"\tradius : double\n"
#define	L64	"\tcolor : vec\n"
#define	L65	"\ttranslation : vec\n"
#define	L66	"\trotation : vec\n"
#define	L67 "\tdiffuse : enum : 1 , 0\n"
#define	L68 "\tspecular : enum : 1 , 0\n"

#define	L69 "paraboloid\n"
#define	L70	"\tposition : vec\n"
#define	L71	"\taxis : vec\n"
#define	L72	"\tradius : double\n"
#define	L73	"\tcolor : vec\n"
#define	L74	"\ttranslation : vec\n"
#define	L75	"\trotation : vec\n"
#define	L76 "\tdiffuse : enum : 1 , 0\n"
#define	L77 "\tspecular : enum : 1 , 0\n"

#define	L78	"hyperboloid\n"
#define	L79	"\tposition : vec\n"
#define	L80	"\tradius : double\n"
#define	L81	"\tcolor : vec\n"
#define	L82	"\ttranslation : vec\n"
#define	L83	"\trotation : vec\n"
#define	L84 "\tdiffuse : enum : 1 , 0\n"
#define	L85 "\tspecular : enum : 1 , 0\n"

#define	L86	"triangle\n"
#define	L87	"\tposition : vec\n"
#define	L88	"\tvalue_of_v1 : vec\n"
#define	L89	"\tvalue_of_v2 : vec\n"
#define	L90	"\tcolor : vec\n"
#define	L91	"\ttranslation : vec\n"
#define	L92	"\trotation : vec\n"
#define	L93 "\tdiffuse : enum : 1 , 0\n"
#define	L94 "\tspecular : enum : 1 , 0\n"

#define	L95	"square\n"
#define	L96	"\tposition : vec\n"
#define	L97	"\taxis : vec\n"
#define	L98	"\tvalue_of_v1 : vec\n"
#define	L99	"\tvalue_of_v2 : vec\n"
#define	L100 "\tvalue_of_w : double\n"
#define	L101 "\tvalue_of_h : double\n"
#define	L102 "\tcolor : vec\n"
#define	L103 "\ttranslation : vec\n"
#define	L104 "\trotation : vec\n"
#define	L105 "\tdiffuse : enum : 1 , 0\n"
#define	L106 "\tspecular : enum : 1 , 0\n"

#define	L107 "cube\n"
#define	L108 "\tposition : vec\n"
#define	L109 "\tradius : double\n"
#define	L110 "\tcolor : vec\n"
#define	L111 "\tdiffuse : enum : 1 , 0\n"
#define	L112 "\tspecular : enum : 1 , 0\n"

#define	L113 "Torus\n"
#define	L114 "\tposition : vec\n"
#define	L115 "\tradius : double\n"
#define	L116 "\tradius : double\n"
#define	L117 "\tcolor : vec\n"
#define	L118 "\tdiffuse : enum : 1 , 0\n"
#define	L119 "\tspecular : enum : 1 , 0\n"

#define	L120 "light\n"
#define	L121 "\tposition : vec\n"
#define	L122 "\tcolor : vec\n"
#define	L123 "\ttype : double\n"
#define	L124 "\tintensity : vec\n"
#define	L125 "\tambient : double\n"

#endif
